spring.application.name=freshly
#spring.data.mongodb.uri=${DB_URL}
spring.data.mongodb.uri=mongodb+srv://nehamethani54:qtruT6zQHv4t7JeD@cluster0.vjmbt2w.mongodb.net/userdb?retryWrites=true&w=majority&appName=Cluster0
logging.level.org.springframework.security.web=INFO
com.nekocodes.freshly.jwt.secret-key = 5367566859703373367639792F423F452848284D6251655468576D5A71347437